ci:
  - '.github/workflows/*.yaml'
  - '.github/workflows/*.yml'
  - 'resources/config/**'
dependencies:
  - 'resources/dependencies/**'
docker:
  - 'docker/Dockerfile*'
docker-gentoo:
  - 'docker/Dockerfile_gentoo'
helpers:
  - '.github/scripts/**'
markdown:
  - '**/*.md'
  - 'resources/data/pyspelling.wordlist.txt'
shell:
  - 'nodebuilder'
test:
  - 'test/test_nodebuilder'
