# Add a comment directly to any PR (also requires permissions: pull-requests: write in validation.yaml
comment_summary_in_pr: always

# Possible values: "critical", "high", "moderate", "low"
fail_on_severity: low

# List of FOSS licenses taken from https://spdx.org/licenses/
allow_licenses:
  - AFL-1.1
  - AFL-1.2
  - AFL-2.0
  - AFL-2.1
  - AFL-3.0
  - AGPL-3.0-only
  - Apache-1.1
  - Apache-2.0
  - APSL-2.0
  - Artistic-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - BSL-1.0
  - CDDL-1.0
  - CPAL-1.0
  - CPL-1.0
  - ECL-2.0
  - EFL-2.0
  - EPL-1.0
  - EPL-2.0
  - EUDatagrid
  - EUPL-1.1
  - EUPL-1.2
  - GPL-2.0-only
  - GPL-3.0-only
  - HPND
  - Intel
  - IPA
  - IPL-1.0
  - ISC
  - LGPL-2.1-only
  - LGPL-3.0-only
  - LPL-1.02
  - MIT
  - MIT-0
  - MPL-1.1
  - MPL-2.0
  - MS-PL
  - MS-RL
  - NCSA
  - Nokia
  - OFL-1.1
  - OSL-1.0
  - OSL-2.0
  - OSL-2.1
  - OSL-3.0
  - PHP-3.01
  - Python-2.0
  - RPSL-1.0
  - SISSL
  - Sleepycat
  - SPL-1.0
  - Unlicense
  - UPL-1.0
  - W3C
  - Zlib
  - ZPL-2.0
  - ZPL-2.1
